### ISSUE TITLE
Add EfficientNet with pretrained weights

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Metalhead.jl#106]
@pxl-th has implemented EfficientNet models in his repo https://github.com/pxl-th/EfficientNet.jl and also implemented the infrastructure to load the weights from pytorch's checkpoints. If the author agrees, we could copy or move the code here and possibly extend the weight loading to other models.

**Comment by pxl-th** [comment]
Absolutely! I've wanted to contribute it for some time myself, but haven't managed yet :)

**Comment by CarloLucibello** [comment]
thanks! Feel free to file a PR whenever you have time

**Comment by darsnack** [comment]
I've added this to the central issue for tracking implementations/weights, so I will close this issue.
