### ISSUE TITLE
Addition of classic LetNet-5 model 

### ISSUE THREAD

**Issue by arcAman07** [FluxML/Metalhead.jl#121]
Just seeing around so many amazing and state of the art models implemented, was wondering whether the classic LeNet 5 model ( still has some use cases as the initial testing architecture for most of the ML developers ) could also be added.

**Comment by darsnack** [comment]
We could add it if there was enough interest, but my vote for now is no. It is simple enough to just write out, and unlike the other models, it does not target ImageNet or require substantial pre-training.

**Comment by arcAman07** [comment]
Cool
