### ISSUE TITLE
Addition of the UNet model architecture

### ISSUE THREAD

**Issue by arcAman07** [FluxML/Metalhead.jl#126]
UNet model archiecture is used for image segmentation. It would be a good idea to add it to the list of already existing models. 
If the model has to be added, I would love to work on the PR.

**Comment by ceferisbarov** [comment]
There already is a Flux-based UNet [implementation](https://github.com/DhairyaLGandhi/UNet.jl) in Julia. I would try to add that model to Metalhead.jl, but it is being maintained separately, so I don't know whether that's the right thing to do.

**Comment by arcAman07** [comment]
I was also going to work on this but there being a UNet implementation in Julia, I didn't feel it had to be added to Metalhead.jl

**Comment by maxfreu** [comment]
Look at [this](https://github.com/maxfreu/SegmentationModels.jl) :blush:
