### ISSUE TITLE
GSoC 2022

### ISSUE THREAD

**Issue by rutvij-25** [FluxML/Metalhead.jl#148]
Hello @darsnack, I would to work on the project "Metalhead.jl Development" this summer as part of GSoC!
I have been an active contributor to Metalhead.jl and model zoo, Here are my pull requests
1) [ESRGANs](https://github.com/FluxML/Metalhead.jl/pull/118) 
2) [Inception v4 and Inception Resnet v2](https://github.com/FluxML/Metalhead.jl/pull/129)
3) [Added weight initialization in DCGAN](https://github.com/FluxML/model-zoo/pull/311) (merged)
4) [I have coded Xception net but yet to start a pull request](https://github.com/FluxML/Metalhead.jl/issues/112)

I would love to work with FluxML!
I would like to ask you about the proposal title and project size.

**Comment by darsnack** [comment]
Hey, I responded to you on Slack. Let's talk about this there.
