### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by theabhirath** [FluxML/Metalhead.jl#160]
Given that the new `sciml` style in JuliaFormatter seems to be working quite well, we could perhaps demo it for this repository? I could try a PR with a `.JuliaFormatter.toml`, but I think the question will be around two major points - indentation for tabs (which is currently 2 but really everywhere else is 4) and spaces around `=` for keyword arguments (which I don't think anyone really agrees on across repositories, so that's just personal preference of picking a style and sticking to it I guess)

**Comment by ToucheSir** [comment]
I think the FluxML "style" (inconsistent as it is) is pretty close to the SciML one in those two areas. This is a good opportunity to try out https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view as well.
