### ISSUE TITLE
Support for convolution on N-dimensions

### ISSUE THREAD

**Issue by shivance** [FluxML/Metalhead.jl#213]
### Motivation and description

1. @ToucheSir comment on #210  [Link](https://github.com/FluxML/Metalhead.jl/pull/210#discussion_r1083516477)
2. FastAI.jl 's support for `ndim` parameter in convx layers Link

See :
 https://github.com/FluxML/FastAI.jl/blob/505621985c27f0d988086345eb44ce7074611173/FastVision/src/models/xresnet.jl#L4

### Possible Implementation

Adding N dim kernels for flux layers (eg conv_norm, basic_conv_bn ...)

Reason : Metalhead's unet adaptation from FastAI.jl uses Metalhead's prebuilt layers like those mentioned above and residual blocks like basicblocks, and these do not have option to specify the number of dimensions of input. They have been developed to keep just 2d images in mind thus 2d kernel.

ndim would enable kernels of multi dimension images.

https://github.com/FluxML/Metalhead.jl/blob/80ab9954320493e0606c7515b6012bebab294a2b/src/layers/conv.jl#L29

.. see Dims{2}

**Comment by darsnack** [comment]
No need for a separate keyword. We can just remove the `2` from the type. Flux's `Conv` already understands kernel size tuples that are length other than 2. FastAI's code generates the tuple which is why they accept a keyword.

Most of the work here is removing the type restrictions and adding tests to make sure it works with dimensions other than 2D.

**Comment by shivance** [comment]
Hi @darsnack,
I removed 2 from the type and tested Metalhead against
```
@testset "UNet" begin
    encoder = Metalhead.backbone(ResNet(18))
    model = UNet((256, 256, 256), 3, 6, encoder)
    x = zeros(256, 256, 256, 1)
    @test size(model(x)) == (256, 256, 256, 6, 1)
    @test gradtest(model, x)

    model = UNet()
    @test size(model(x)) == (256, 256, 3, 1)
    _gc()
end
```

unit test. It Failed with error
```
UNet: Error During Test at /home/anshuman/Desktop/Metalhead.jl/test/convnets.jl:1
Got exception outside of a @test
DimensionMismatch: Rank of x and w must match! (5 vs. 4)
Stacktrace:
```

**Comment by shivance** [comment]
Hi @darsnack,
I removed 2 from the type and tested Metalhead against
```
@testset "UNet" begin
    encoder = Metalhead.backbone(ResNet(18))
    model = UNet((256, 256, 256), 3, 6, encoder)
    x = zeros(256, 256, 256, 1)
    @test size(model(x)) == (256, 256, 256, 6, 1)
    @test gradtest(model, x)

    model = UNet()
    @test size(model(x)) == (256, 256, 3, 1)
    _gc()
end
```

unit test. It Failed with error
```
UNet: Error During Test at /home/anshuman/Desktop/Metalhead.jl/test/convnets.jl:1
Got exception outside of a @test
DimensionMismatch: Rank of x and w must match! (5 vs. 4)
Stacktrace:
```

**Comment by shivance** [comment]
Hi @darsnack,
I removed 2 from the type and tested Metalhead against
```
@testset "UNet" begin
    encoder = Metalhead.backbone(ResNet(18))
    model = UNet((256, 256, 256), 3, 6, encoder)
    x = zeros(256, 256, 256, 1)
    @test size(model(x)) == (256, 256, 256, 6, 1)
end
```

unit test. It Failed with error
```
UNet: Error During Test at /home/anshuman/Desktop/Metalhead.jl/test/convnets.jl:1
Got exception outside of a @test
DimensionMismatch: Rank of x and w must match! (5 vs. 4)
Stacktrace:
```

**Comment by darsnack** [comment]
Did you also update the corresponding `UNet` code to generate kernel size tuples of length `N`?

**Comment by shivance** [comment]
Yup I tried that as well :)
But still the same error. I even know the reason for that : we are using backbone of metalhead models for encoder.
If you take a look, all of them have hardcoded 2d kernels...
