### ISSUE TITLE
Out of date dependencies in metalhead 0.7.3

### ISSUE THREAD

**Issue by christiangnrd** [FluxML/Metalhead.jl#216]
Since it seems like there's still a decent amount of work needed for v0.8.0, I think it would be worth updating the Project.toml compat section from:
```
[compat]
BSON = "0.3.2"
Flux = "0.13"
Functors = "0.2"
MLUtils = "0.2.6"
NNlib = "0.7.34, 0.8"
julia = "1.6"
```

to:
```
[compat]
BSON = "0.3.2"
Flux = "0.13"
Functors = "0.2, 0.3, 0.4"
MLUtils = "0.2.10, 0.3, 0.4"
NNlib = "0.7.34, 0.8"
julia = "1.6"
```

so that the current version of Metalhead can be used with the latest 0.13 version of Flux.
I tried it and ran the tests locally and they all passed, but I'm sure there's other considerations to be made.

Is this feasible?

**Comment by christiangnrd** [comment]
I updated a branch that was created from the v0.7.3 tag in my fork of Metalhead, but I'm don't seem to be able to create a pull request to a tag. 

Here's a link to the changes that would allow v0.7.* of Metalhead to support use Flux past v0.13.4: https://github.com/christiangnrd/Metalhead.jl/tree/dep-update-0.7.3

**Comment by darsnack** [comment]
Once the tests pass on https://github.com/FluxML/Metalhead.jl/commit/5d8a67102e022169799429cbe80771a65b18f354, I'll make a release.

**Comment by christiangnrd** [comment]
The tests timed out on buildkite. I ran `test Metalhead` on my 3700X Ubuntu 22.10 desktop and all tests passed in ~1h. I also ran it on my apple silicon laptop and it also passed all the tests.

**Comment by christiangnrd** [comment]
Test successfully ran on Windows 11.

**Comment by darsnack** [comment]
Just released a patch
