### ISSUE TITLE
Fixing deprecated models

### ISSUE THREAD

**Issue by natema** [FluxML/Metalhead.jl#218]
Following some old posts on the Julia Discourse (and what tab-autocompletion suggests after `using Metalhead`), I did 
```jl
using Flux, Metalhead
model = VGG16()
```
I got 
```
ERROR: UndefVarError: `VGG16` not defined
```
as confirmed from the fact that [`VGG16` and other functions are deprecated](https://github.com/FluxML/Metalhead.jl/blob/99721be2c3c1018b7b112cf6ca94779ca3808da4/src/deprecations.jl#L10), but [they are still exported](https://github.com/FluxML/Metalhead.jl/blob/99721be2c3c1018b7b112cf6ca94779ca3808da4/src/Metalhead.jl#L70). 

If appropriate, I could do a PR to stop exporting them.

**Comment by ToucheSir** [comment]
Good catch and please do! I think everything in that file should get the same treatment.
