### ISSUE TITLE
Release v0.8

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Metalhead.jl#240]
The issues for the milestone have been cleared. Anything else before tagging?

**Comment by theabhirath** [comment]
I am working on fixing the DenseNets, and porting their weights. That, along with some docs updates, should land in under a week and should be the last thing we handle in v0.8.

**Comment by CarloLucibello** [comment]
Since we can load the old version of DenseNet and the change should be non-breaking we can consider that non-blocking for the v0.8 release and be part of a patch release shortly after.
