### ISSUE TITLE
Saving large models with JLD2 fails

### ISSUE THREAD

**Issue by oluwandabira** [FluxML/Metalhead.jl#252]
Saving model with JDL2 fails if the model is large enough (at least I think that's what's happening)
```julia
using Flux
using Metalhead
using JLD2

model = ResNet(152)
model_state = Flux.state(model)
jldsave("model_state.jld2"; model_state)
```
The above will fails with:
```
InexactError(:trunc, UInt16, 66886)
```

Also fails for `EfficientNet(:b8)`

`Pkg.status()`:
```
[587475ba] Flux v0.14.6
[033835bb] JLD2 v0.4.35
[dbeba491] Metalhead v0.8.3
```

**Comment by darsnack** [comment]
Can you post a full stack trace instead of the final error?

**Comment by oluwandabira** [comment]
https://gist.github.com/oluwandabira/aad1059b2410f1ad13d5232a6d1b071c

**Comment by darsnack** [comment]
I assume that `ResNet(18)` works? It's probably [this issue](https://github.com/JuliaIO/JLD2.jl/issues/399). In which case that's a JLD2 issue, and there isn't much we can do here.

**Comment by oluwandabira** [comment]
All the other ResNets work. It does appear to be a JLD2 issue so I've opened an issue there.
