### ISSUE TITLE
VGG has two "higher-level" functions

### ISSUE THREAD

**Issue by theabhirath** [FluxML/Metalhead.jl#269]
VGG currently has two functions in the "higher-level" API category (as per the camel-casing nomenclature):

```julia
VGG(imsize::Dims{2}; config, inchannels, batchnorm = false, nclasses, fcsize, dropout_prob)
VGG(depth::Integer; pretrain::Bool = false, batchnorm::Bool = false, inchannels::Integer = 3, nclasses::Integer = 1000)
```

The former is probably an artifact of pre-0.8 Metalhead, since there is also a mid-level function for VGG with a very similar API:

```julia
vgg(imsize; config, inchannels, batchnorm = false, nclasses, fcsize, dropout_prob)
```

This came up in #268, where the pre-trained version of VGG has its docstring hidden. We can work around this I believe by writing a single docstring with both variants, but if it is agreeable maybe we can deprecate the first function above for uniformity?

**Comment by darsnack** [comment]
Let's deprecate the first version.
