### ISSUE TITLE
Pretrained VGG is very bad

### ISSUE THREAD

**Issue by Keno** [FluxML/Metalhead.jl#3]
It gets most things quite wrong. On slack it was suggested that we may have to look at the way we're doing preprocessing to see if we got something wrong there.

**Comment by MikeInnes** [comment]
One useful source for parameters is [here](https://github.com/keras-team/keras/blob/919769c7b78ba4bc26b214c7c28b7345bb35d272/keras/applications/imagenet_utils.py#L21). Something could well have been lost in translation.

**Comment by avik-pal** [comment]
This is not specific to VGG I tried the Resnet and it seems to predict quite randomly. I tested some of the Imagenet dog images and it doesn't give correct predictions even in top 100
