### ISSUE TITLE
Different Models have different preprocessing needs

### ISSUE THREAD

**Issue by avik-pal** [FluxML/Metalhead.jl#32]
Here is a [gist](https://gist.github.com/avik-pal/32a9bbc9ef9f38351fbc7f68b3211f94) for the preprocessing needed for Resnet50 (use the updated model from #17).

The current preprocess function handles VGG and SqueezeNet fine, but ResNet50 needs the inputs scaled between -1 and 1 and **NOT** -255 to 255.

What would be the proper way to handle this? (Once we add more pretrained models they will have custom preprocessing needs)

**Comment by darsnack** [comment]
Closing in favor of #117
