### ISSUE TITLE
load custom dataset

### ISSUE THREAD

**Issue by kritiyer** [FluxML/Metalhead.jl#38]
Does Flux or Metalhead have a way to serially load large datasets (too large to be fully loaded into memory as numpy arrays)? I saw that Metalhead.datasets() supports reading in standard datasets, but could it be modified to load custom datasets?

**Comment by lorenzoh** [comment]
See the (soon-to-be-published) [DataLoaders.jl](https://github.com/lorenzoh/DataLoaders.jl)

**Comment by darsnack** [comment]
DataLoaders.jl is an option if your model doesn't fit in memory. Metalhead.jl will no longer provide datasets, so I'm closing this issue.
