### ISSUE TITLE
Loader For Pascal VOC dataset

### ISSUE THREAD

**Issue by shreyas-kowshik** [FluxML/Metalhead.jl#39]
I think we Metalhead.jl also needs to have a loader for PASCAL-VOC dataset as it is commonly required for object detection and localisation tasks. If required, I cango forward towards adding it...

**Comment by shreyas-kowshik** [comment]
#40 Added the Pascal-VOC-2012 dataset

**Comment by djwessel** [comment]
@shreyas-kowshik is there any update here? I'm looking to use Pascal-VOC-2012 in one of my projects.

**Comment by darsnack** [comment]
Closing this as Metalhead.jl no longer provides datasets. See MLDatasets.jl instead.
