### ISSUE TITLE
Add support for miniImagenet

### ISSUE THREAD

**Issue by IsakFalk** [FluxML/Metalhead.jl#55]
In meta-learning, miniimagenet is a common benchmark derived from the imagenet dataset. A library that does this (arguably the standard library for this) is https://github.com/yaoyao-liu/mini-imagenet-tools.

It would be beneficial to have support for this dataset in Metalhead.jl.

**Comment by darsnack** [comment]
Metalhead.jl no longer provides datasets, but minified ImageNet datasets are available in FastAI.jl (and soon to be ported to MLDatasets.jl).
