### ISSUE TITLE
Feature request: ESRGAN, upconv7, upcunet

### ISSUE THREAD

**Issue by seadra** [FluxML/Metalhead.jl#81]
Maybe too ambitious but it would be nice to have ESRGAN, upconv7 and upcunet (used by [waifu2x](https://github.com/nagadomi/waifu2x/tree/master/appendix/caffe_prototxt))

**Comment by DhairyaLGandhi** [comment]
We don't have any GANs in Metalhead yet, we can consider having those in as well.

**Comment by rutvij-25** [comment]
Hello, @DhairyaLGandhi I was thinking about implementing ESRGANs, can I go for it?

**Comment by DhairyaLGandhi** [comment]
Sure go ahead

**Comment by rutvij-25** [comment]
https://github.com/rutvij-25/ESRGAN.jl
Still working on this tho :)

**Comment by darsnack** [comment]
I'm closing this in favor of #112 which tracks the request.
