### ISSUE TITLE
Where is the Metalhead.jl documentation? 

### ISSUE THREAD

**Issue by logankilpatrick** [FluxML/Metalhead.jl#84]
Hey @DhairyaLGandhi can we get a link both in the Readme to the docs for this package as well as on the main repo page? 

It also looks like there may not be docs right now, if this is the case, is there any plan to start going through this process? I can kick off that process if that would help.

**Comment by logankilpatrick** [comment]
Done

**Comment by darsnack** [comment]
https://fluxml.ai/Metalhead.jl/dev/README.html looks like we have docs! The Flux theme is not being used so I can debug that later. But I'll close this issue now.

**Comment by logankilpatrick** [comment]
Why are we using publish.jl instead of documenter?

**Comment by darsnack** [comment]
The models are so large, that we need a GPU to do anything other than running a single example forward through the network. My long term goal (when I find the time 😅) for this repo is to add more tutorial-like docs that show users how to load a pre-trained model and do transfer learning, etc. For that, the most convenient solution seemed to be writing the docs in the Jupyter notebook with my local GPU. Then the code and output are saved and committed, and Publish.jl is the only system that accepts Jupyter notebooks as input. FastAI.jl adopted a similar choice for the same reasons.

Other options would require building the docs with CI using a GPU, or running the docs locally and having to copy-paste the REPL output. We can switch doc systems without breaking, so if someone has a good alternative, then we can do that instead.
