### ISSUE TITLE
ResNet skip connection definition seems wrong

### ISSUE THREAD

**Issue by maxfreu** [FluxML/Metalhead.jl#89]
Hi, the definition of the ResNet [skip connection](https://github.com/FluxML/Metalhead.jl/blob/88b7ca685db39c622f5a51d45122703784a6e268/src/resnet.jl#L67-L71) via 1x1 MaxPool with stride, concatenated with zeros seems very strange to me. In the paper they mention a matrix multiply, which is closer to a 1x1 conv. PyTorch [uses 1x1 conv](https://github.com/pytorch/vision/blob/3d9d264198e2167030dc04bf453aeca47daa37db/torchvision/models/resnet.py#L215-L216) indeed, together with a stride of 2 (or optional dilation) where necessary. Should be easy to fix, maybe I can provide a PR.

**Comment by darsnack** [comment]
That's the identity skip connection used by the simplest variant in the paper (which PyTorch doesn't support IIRC). The normal skip connection with 1x1 convolutions is provided as `skip_projection`, and it is used by the default models where specified in the paper.

**Comment by darsnack** [comment]
We should probably rename it to `identity_projection` before releasing.

**Comment by maxfreu** [comment]
Ok, I found the relevamt passage in the paper where they describe the skip connections, but not where they hard link it to the layer count. Maybe have to read again with more time. Anyhow, I think performance wise everyone would want type B in their models, so I’d make that default. But  as long as I can change it via config paramams, that’s also ok.

**Comment by darsnack** [comment]
It's mentioned in Fig. 5's caption and the section "Residual Networks" on the previous page. But yes, all of it is configurable.

**Comment by maxfreu** [comment]
Thanks! Since it’s configurable, maybe more a matter of taste and I missed the presence of option B in the code, I’m closing.
