### ISSUE TITLE
trainimgs not defined

### ISSUE THREAD

**Issue by Ossifragus** [FluxML/Metalhead.jl#98]
Not sure if this is the right place to report. When I use
```julia
using Metalhead: trainimgs, valimgs
```
I got
```julia
julia> using Metalhead: trainimgs, valimgs
ERROR: UndefVarError: trainimgs not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/CUDA/YpW0k/src/initialization.jl:52
```
This occurs in both Julia 1.6.2 and 1.7.

**Comment by ToucheSir** [comment]
Those functions no longer exist in Metalhead, were you looking at some resources that suggested using them?

**Comment by Ossifragus** [comment]
Oh, got it. Thank you for the quick response. I was trying to go over this tutorial:
<https://fluxml.ai/tutorials/2020/09/15/deep-learning-flux.html>

Is [MLDatasets](https://github.com/JuliaML/MLDatasets.jl) or any other package or function a replacement?

**Comment by ToucheSir** [comment]
Yes, though the API will be different. Do you mind filing an issue on
https://github.com/FluxML/fluxml.github.io/issues about this tutorial
so we can track it? It should definitely be updated.

**Comment by Ossifragus** [comment]
I just did, and I will see if I can make MLDatasets work. Thank you.

**Comment by darsnack** [comment]
`traintensor` from MLDatasets is what you're looking for.

**Comment by Ossifragus** [comment]
> `traintensor` from MLDatasets is what you're looking for.

Thank you!
